# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlesEspeciais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AVP', 'AVP'), ('AVC', 'AVC'), ('CLP', 'CLP'), ('CDL', 'CDL')], max_length=4)),
                ('data', models.DateField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('Colocado', 'c'), ('Trocado', 't')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrescricaoDeEnfermagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescricacao.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SinaisVitais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('marcado', models.BooleanField(default=False)),
                ('Prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescricacao.PrescricaoDeEnfermagem')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSinalVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sinaisvitais',
            name='tiposinalvital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescricacao.TipoSinalVital'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='prescricaodeenfermagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescricacao.Paciente'),
        ),
        migrations.AddField(
            model_name='controlesespeciais',
            name='prescricaodeenfermagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescricacao.PrescricaoDeEnfermagem'),
        ),
    ]
