# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescricacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numleito', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
    ]
