# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescricacao', '0004_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
