# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prescricacao', '0008_auto_20170423_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescricaodeenfermagem',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='prescricaodeenfermagem',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescricacao.Diagnostico'),
        ),
        migrations.AddField(
            model_name='prescricaodeenfermagem',
            name='prescricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Prescricacao.Prescricao'),
            preserve_default=False,
        ),
    ]
