# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescricacao', '0009_auto_20170423_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnostico',
            new_name='Diagnsotico',
        ),
        migrations.AlterField(
            model_name='prescricaodeenfermagem',
            name='diagnostico',
            field=models.CharField(max_length=255),
        ),
    ]
