# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prescricacao', '0010_auto_20170423_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnsotico',
            new_name='Diagnostico',
        ),
    ]
